### ISSUE TITLE
Angular Universal SSR: Window not defined error

### ISSUE THREAD

**Issue by marcelvarela** [chrum/ngx-autosize#51]
It seems this directive uses window DOM without any wrapper which is not ideal for server side rendering, even though the app is still able to run and I only get this error on firebase functions dashboard.

```
ReferenceError: window is not defined
    at _zone.runOutsideAngular (/workspace/dist/diastour/server/main.js:1:985553)
    at ZoneDelegate.invoke (/workspace/dist/diastour/server/main.js:1:3824872)
    at Zone.run (/workspace/dist/diastour/server/main.js:1:3817286)
    at NgZone.runOutsideAngular (/workspace/dist/diastour/server/main.js:1:4375488)
    at AutosizeDirective._addWindowResizeHandler (/workspace/dist/diastour/server/main.js:1:985530)
    at AutosizeDirective._onTextAreaFound (/workspace/dist/diastour/server/main.js:1:985072)
    at new AutosizeDirective (/workspace/dist/diastour/server/main.js:1:984267)
    at NodeInjectorFactory.AutosizeDirective_Factory [as factory] (/workspace/dist/diastour/server/main.js:1:987585)
    at getNodeInjectable (/workspace/dist/diastour/server/main.js:1:4060133)
    at instantiateAllDirectives (/workspace/dist/diastour/server/main.js:1:4097264)
    at resolvePromise (/workspace/dist/diastour/server/main.js:1:3834700)
    at resolvePromise (/workspace/dist/diastour/server/main.js:1:3833677) 
```

**Comment by chrum** [comment]
ok, good point :) i forgot about ssr completely... do you have some quick demo repo where its easy to test?

**Comment by chrum** [comment]
hey @MVDeveloper1 
check 'next' channel please:
`npm install ngx-autosize@next`
